### ISSUE TITLE
rdryad::dryad_download() cannot be used in a CRAN package

### ISSUE THREAD

**Issue by krzbar** [ropensci/rdryad#35] opened 2021-11-09 08:43 UTC
Hello!
It seems that one cannot use rdryad::dryad_download() in a R package. What happens is that rdryad::dryad_download() can only download to ~/Library/Caches/R . I used this in the vignette to my mvSLOUCH R package, however I obtained from CRAN: 
The CRAN policy only allows writing in file areas via tools::R_user_dir() (which differ by OS).   On macOS, ~/Library/Caches/R is not one of those, yet we see there
drwxr-xr-x  4 ripley  staff  128  8 Nov 06:54 rdryad/
from
mvSLOUCH via rdryad (which does not create this in its own checks).
This makes it much harder to sweep up after you.

I would suggest adding the possibility to specify a target download destination for rdryad::dryad_download().

Best wishes
Krzysztof Bartoszek

**Comment by mpadge** [comment] 2021-11-09 11:03
@krzbar As this is a duplicate of #34, I'll close this issue and continue conversations over there. Thanks!

**Closed by mpadge** 2021-11-09 11:03 UTC
